include: "rules/common.smk"

##### Target rules #####
rule all:
    input:
        "results/qc/qc.html",
        "results/plots/depths.svg",


##### Modules #####

include: "rules/ref_genome.smk"
include: "rules/read_qc.smk"
include: "rules/mapping.smk"
include: "rules/bam_qc.smk"
