name: tcge-cfmedip-seq-pipeline
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - snakemake=6.12.3
  - bwa=0.7.17
  - trim-galore=0.6.7
  - samtools=1.9
  - graphviz=2.40.1
  - picard=2.26.6
  - gnuplot=4.6.0
